[build]
command = "hugo --enableGitInfo -d dist -s site -v --minify"
publish = "site/dist"

[context.deploy-preview]
command = "hugo --gc --enableGitInfo -d dist -s site -v --buildDrafts --buildFuture"

[context.production.environment]
HUGO_VERSION = "0.108.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
HUGO_VERSION = "0.108.0"
