name = "Casper NG CMS"
license = "MIT"
licenselink = "https://github.com/fluential/casper-ng-hugo/blob/master/LICENSE"
description = "Casper NG CMS - Hugo version of Casper theme for Ghost. Cleaned and simplied. Supports latest Hugo in most native way"
homepage = "https://github.com/fluential/casper-ng-hugo"
tags = ["blog", "light", "minimal", "simple", "personal" ,"responsive", "portfolio"]
features = ["mermaid", "optional google fonts", "syntax highlighting", "disqus", "rss", "google analytics", "share"]
min_version=0.95
demosite= "https://casper-ng-hugo.netlify.app"

[author]
  name = "fluential"
  homepage = "https://github.com/fluential"

[original]
  name = "Casper CMS"
  homepage = "https://github.com/bdougie/casper-cms-template"
  repo = "https://github.com/bdougie/casper-cms-template"
